### ISSUE TITLE
File attachments in chat 

### ISSUE THREAD

**Issue by leihla** [okTurtles/group-income#1640]
### Problem

We need a simple UI for uploading file attachments and displaying them.

### Solution
I've designed two flows for send picture attachment or file attachments. Users should be able to attach a file either by clicking on the attachment icon on the message bar or dragging and dropping an attachment in the chat area.

**Send Image**
https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=26191%3A296507&t=teMy1XvN3V9PR9oY-1

<img width="1533" alt="Screenshot 2023-06-05 at 16 12 43" src="https://github.com/okTurtles/group-income/assets/158178/536942c5-0292-4ea2-aa6d-27386d993329">
<img width="1520" alt="Screenshot 2023-06-05 at 16 12 50" src="https://github.com/okTurtles/group-income/assets/158178/250ddcf2-42fe-4238-a5ea-fb752679e5d2">
<img width="744" alt="Screenshot 2023-06-05 at 16 12 57" src="https://github.com/okTurtles/group-income/assets/158178/7e7c6280-ca50-4aa8-bb77-1d4887fbbedd">

**Send Attachment**
https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=26191%3A301188&t=teMy1XvN3V9PR9oY-1

<img width="1525" alt="Screenshot 2023-06-05 at 16 13 31" src="https://github.com/okTurtles/group-income/assets/158178/c566cee7-133c-460a-8122-54f10bdd501a">

Related to #1557

**Comment by SebinSong** [comment]
# Dev TODO List

## Part 1. UI components that don't involve changing `chatroom.js` contracts

 - [x] **Task 1-1. Load and preview image attachment**
 Load image from the file-system and display the preview of the image and make it removable via 'x' button at the corner.
 
<img src='https://github.com/okTurtles/group-income/assets/17641213/f887fd5e-73b3-4fe8-b7d5-08feb3e634f0' width='480'>

<img src='https://github.com/okTurtles/group-income/assets/17641213/72c40596-3273-41eb-9c17-ae1ce74fd482' width='480'>



 - [x] **Task 1-2. Load and preview **non-image type** attachment**
Extend the **Task 1-1** to non-image type attachments.

<img src='https://github.com/okTurtles/group-income/assets/17641213/e8057df2-03d9-4a3c-abb4-04d509b48d7f' width='480'>


 - [x] **Task 1-3. Implement file-size detection and build 'File too large' modal**

<img src='https://github.com/okTurtles/group-income/assets/17641213/fb2996de-9bbb-4fd8-b010-8d3d88342acc' width='480'>


 - [x] **Task 1-4. Implement task 1-1, 1-2, 1-3  by drag&drop action**

<img src='https://github.com/okTurtles/group-income/assets/17641213/09482bec-f8a8-4eb5-ac6a-a5ce14fbcb92' width='480'>


## Part 2. UI components that involve changing `chatroom.js` contracts

 - [ ] **Task 2-1. Implement 'Send a message with image attachment'**
Implement 'file attachment' in `chatroom.js` contracts and also update `Message.vue` component with image-preview element.

<img src='https://github.com/okTurtles/group-income/assets/17641213/34c347de-7295-41d6-849c-2549a8c0863f' width='480'>

 - [ ] **Task 2-2. Implement 'Send a message with non-image type attachment'**
Implement 'file attachment' in `chatroom.js` contracts and also update `Message.vue` component with the **file preview** element.

<img src='https://github.com/okTurtles/group-income/assets/17641213/cc392c3e-28ba-4076-9a77-5782fead2c9a' width='480'>

 - [ ] **Task 2-3. Implement 'Download the attachment'**
Add the download button to `Message.vue` component and make it possible to download the attached file.

<img src='https://github.com/okTurtles/group-income/assets/17641213/573e7244-2b9f-4afc-b4a8-9f98e1e5569e' width='480'>

**Comment by SebinSong** [comment]
I'm going to develop this feature step by step according to the [Todo list](https://github.com/okTurtles/group-income/issues/1640#issuecomment-1667356671) created above.
cc. @taoeffect

**Comment by SebinSong** [comment]
@taoeffect 
I've got a question regarding this modal below.
It looks to me that this modal having two buttons is unnecessary as they both are supposed to result in the same action, which is 'Closing the modal and discard the file the user has selected.' Do you agree we can remove the 'Cancel' button here?

<img src='https://github.com/okTurtles/group-income/assets/17641213/c537fcaa-06fe-4a40-b9f6-222e15da5663' width='410' >

**Comment by taoeffect** [comment]
@SebinSong Yep, agreed! 👍

**Comment by SebinSong** [comment]
@taoeffect 
I think all Task - 1 items are complete and ready for sending a PR.
As described in the todo details, implementing the functionality in the `chatroom.js` is better to be done after E2E encryption work is complete in the backend. So for now, when the `Send` button is clicked with a file attached,

<img src='https://github.com/okTurtles/group-income/assets/17641213/7b462466-d6f1-4bd8-ab74-abd9bf3d5d90' width='410'>

I've made it so that it results in this appended text message saying the attached file name and the feature will be prepared in the future.

<img src='https://github.com/okTurtles/group-income/assets/17641213/125c861f-116d-4515-9928-ffa6e363ed69' width='480'>

Does this sound good to you?
If it does, I can put the work together and send a PR.

**Comment by taoeffect** [comment]
@SebinSong yeah, sending a message that just has that text sounds good 👍 
Hopefully this doesn't require modifying `chatroom.js` at all

**Comment by taoeffect** [comment]
Pretty sure this has been closed.
