### ISSUE TITLE
Implement credits system

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1801]
### Problem

We need to implement a system to start tracking the cost of hosting data on the backend.

We need to be able to:

- Add credits to an account (an account represented by a username, which points to an identity contract)
- Have that account "own" other contracts (e.g. if an account creates other contracts, it is responsible for them, and the costs of hosting those other contracts are deducted from the original account that created them)
- Have that account "own" any files that are uploaded that are associated with any contracts

### Solution

Create this system. We need to have an admin UI that is able to create credits out of thin air and give them to other accounts. Then have a pricing system so that we can tell how many credits to deduct based on how much data someone is storing over time. Later on (as a separate issue) we can add code to purchase these credits.

In terms of storing information, we want to use the Shelter Protocol for doing this (and not some other protocol, e.g. HTTP headers) to reduce complexity and increase flexibility. Exactly how this is done remains to be decided. There are several possibilities and various considerations. For example, we might not want contract ownership info to be public info. We also might want to preserve this information during migration between servers.

Various possible methods:

- There could be a shared contract between users and the server that is used for storing ownership information, with a server-key that is used to encrypt the info so that only the server knows who owns what contracts and data.
- We could use the planned secure key/value store: #1656
- We could use `OP_PROP_SET` to use the contract key-value store and store the info in a key with an encrypted value.

#### Subtasks

- [ ] create a concept of a server admin that can create credits
- [x] decide how credits are stored on the server db and how permissions are handled relating to updating those keys (#1656 possibly needs to be closed first)
- [x] decide how ownership is represented (see above)
- [x] Keep track of file ownership (see also #1827 for other reasons this is needed)
- [x] implement function to calculate how much data an identity contract owns
- [ ] deduct credits based on the value of that function and an admin-set cost/rate

Ideas:

- When an event is uploaded, we should have a key for contracts that keep track of the size of the entire contract (e.g. `contractSize:<contractID>`, and increment it with each message that's added to the contract
- Allow the server admin to specify a credits/bytes value for traffic going out from the server.
- Make sure we can transfer ownership of files to some other account (seems like a useful feature potentially)
