### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#400]
### Problem

It can often be useful to interact with your group members by asking them to vote in a poll, similar to how Twitter handles polls. We do have a proposals system where votes can be cast, but these have real consequences. It would be nice to have a simple polls feature in the chat with no consequences (simply to gage sentiment on whatever question members have).

### Solution

Implement this feature.

**Comment by dotmacro** [comment]
[Figma link for polls design & flow](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=14088%3A154296)

**Comment by SebinSong** [comment]
Hi @dotmacro , 
I was wondering if this task is ready to be implemented in the front-end and if so, could you please share the link to the design of this again please? 
the one you commented above seems to have been revoked. Thanks.

**Comment by dotmacro** [comment]
The polls design and flow is here: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23766%3A273992&t=kIFu9duj35DntNRc-3

It looks ready to me! There is one question about checkbox & text positioning, which you may be able to figure out based on the [design notes](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23766%3A265613&t=kIFu9duj35DntNRc-3).

**Comment by SebinSong** [comment]
# Dev TODO List

## Part 1. Build required UI components


 - [x] **Task 1-1. 'Create new polls' popover component**

<img src='https://user-images.githubusercontent.com/17641213/208851018-b119026a-cf18-4b2f-8c4a-ba91f76df1c5.png' width='340'>

- [x]  **Task 1-2. Message component with type='poll'** _- when the user hasn't voted yet_

<img src='https://user-images.githubusercontent.com/17641213/208851617-8c010879-9eab-496f-ad64-c2545f6b0f79.png' width='410'>

- [x]  **Task 1-3. Message component with type='poll'** _- after the user has voted (message variation, notification for vote)_

<img src='https://user-images.githubusercontent.com/17641213/208852174-85c85a2b-9c64-4d96-89bb-c32107807d6e.png' width='410'>

<img src='https://github.com/okTurtles/group-income/assets/17641213/c3d06918-08fc-4ccb-8c7f-137dfd5e4177' width='410'>

- [x]  **Task 1-4. Implement 'change vote' functionality**

<img src='https://github.com/okTurtles/group-income/assets/17641213/968cdec8-be96-41a1-99a6-a6852bb5e087' width='410'>

- [x] **Task 1-5. Poll closure**

<img src='https://github.com/okTurtles/group-income/assets/17641213/7c8c6566-0143-4d0d-ad22-c29ec1819c26' width='410'>

- [x]  **Task 1-6. 'Who voted' pop-up box**

<img src='https://user-images.githubusercontent.com/17641213/208852531-2704c2d5-7514-4ac2-a568-154a3e3ff3b6.png' width='410'>

- [ ] **Task 1-7. Implement 'Edit poll' functionality for the poll creator**

<img src='https://github.com/okTurtles/group-income/assets/17641213/d92d9c6b-cde1-4c21-bcb2-9b87842ceb40' width='320'>

## Part 2. Implement polls in `chatroom.js` contracts
build the required logics for polls and connect them with the UIs built in **Part 1.**

- [x] implement `MESSAGE_TYPES.POLL` in `gi.contracts/chatroom/addMessage`
- [x] implement `gi.contracts/chatroom/gi.contracts/chatroom/voteOnPoll` in `chatroom.js`
- [x] implement `gi.contracts/chatroom/gi.contracts/chatroom/changeVoteOnPoll` in `chatroom.js`
- [x] implement poll closure in `chatroom.js`

**Comment by Silver-IT** [comment]
@SebinSong, since I could be more familiar with `chatroom.js`, I can work on the Part 2 after you finish Part 1 if you don't mind.

**Comment by SebinSong** [comment]
@Silver-IT Hi Alex, 
one of the reason why I picked this issue up was that I wanted to explore the chatroom area in both UI and contracts sides of the project. Currently I'm on some other higher priority tasks but once I get back to this, would love to take care of both Part 1. & 2 for that reason. But will definitely reach out to you when I need to borrow you expertise in this area. Thanks.

**Comment by SebinSong** [comment]
@Silver-IT Hi Alex, Just had a chat with @taoeffect and I agree me working on the Part 1 and then you taking care of the Part 2 works the best. we can proceed with your suggestion.

**Comment by Silver-IT** [comment]
Thanks, @SebinSong.

**Comment by SebinSong** [comment]
Hi @taoeffect ,
I'm currently working on building this `MESSAGE_TYPES.POLL` UI components, and noticed that each options are presented as a 'checkbox'. 

<img src='https://github.com/okTurtles/group-income/assets/17641213/39532e18-61a7-47f2-adfa-f9a92db70da2' width='410'>

**Q1.** Does that mean we allow users to choose multiple options?

**Q2.** if we do allow for multiple selections, then shouldn't it need some sort of button that confirm&process the votes on the poll like below?

<img src='https://github.com/okTurtles/group-income/assets/17641213/0972a994-0338-4a01-bdb0-da8b400fcd1e' width='410'>

**Comment by taoeffect** [comment]
> Q1. Does that mean we allow users to choose multiple options?

Looking at the designs, it looks like we missed a checkbox that says, "Allow multiple choice"

Please add that checkbox yourself and create a poll that uses either radio buttons or checkboxes depending on whether or not it was checked.

> Q2. if we do allow for multiple selections, then shouldn't it need some sort of button that confirm&process the votes on the poll like below?

Yes, I agree 👍

**Comment by SebinSong** [comment]
Hi @taoeffect ,
I think tasks **1-1.** and **1-2.** have been done to a level where they are good to review, as you can check out from the video attached.

https://github.com/okTurtles/group-income/assets/17641213/761cf3c1-928f-4039-871a-9a82c7107868

To avoid having to review too many changes all at once, instead of making a single PR for this issue, I thought it would be better to split this issue into two chunks, which are 
- task **1-1.** & **1-2.** : implement 'Create poll' pop-up(including changes to `chatroom.js` contract needed for creating a poll) & `MESSAGE_TYPES.POLL` message UI component.
- the rest

What's your thoughts? If you agree, I will make a PR for the first chunk.

**Comment by taoeffect** [comment]
@SebinSong Yes, that works 👍 

We need to get better at making sure the UI works on mobile too, so please remember to test [mobile] thoroughly using the browser's responsive mode.

**Comment by SebinSong** [comment]
Hi @taoeffect ,
Over the past several weeks, Another large enough chunk of work has been done and at a point where they are good to review. To list what have been developed,

- Voting on the poll
- Changing previous votes on the poll
- Expiration of the poll
- Building all UI components that are related to above.

Below is a video where I demonstrate these.

https://github.com/okTurtles/group-income/assets/17641213/badc590c-c638-47fd-99dd-b712461a6e87


Can I create a PR for this chunk so that it can be reviewed?
(The final chunk of for this issue after this will mainly be _creating a cypress test-suite_ for Poll functionality along with implementing some other minor features it's missing)

**Comment by taoeffect** [comment]
> Can I create a PR for this chunk so that it can be reviewed?

@SebinSong Yep!

Fantastic work btw! 😄 👍
