### ISSUE TITLE
Find/create/fix ORM so that it correctly uses SQL (i.e. parameterizes its queries)

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#82]
See [rant](https://twitter.com/taoeffect/status/738478839148339200).

EDIT: after some research, these seem to be the options:
### ~~Option 1: Modify node-sql~~
- [ ] Modify [node-sql](https://github.com/brianc/node-sql) (or create a wrapper around it) to conform to [knex](https://github.com/tgriesser/knex) API. At least [3 three ORMs](https://github.com/okTurtles/group-income-simple/issues/82#issuecomment-223443658) will then "do SQL right".
- [x] Evaluate which of [the three ORMs](https://github.com/okTurtles/group-income-simple/issues/82#issuecomment-223443658) we then need to modify (& send a PR) to switch to our Knex-compatible node-sql query builder.
  - Out of the 3, bookshelf seems to be the winner, with a decent community and a fairly similar API to Sequelize.
### ~~Option 2: Modify Knex~~
- [ ] In which case close this issue and focus solely on #83.
### ~~Option 3: Modify Sequelize~~

If both Options 1 & 2 turn out to be more work than simply modifying Sequelize to use node-sql, then maybe that makes more sense.
### Option 4: Create an ORM directly on top of node-sql ✅

It could also make the most amount of sense to simply create our own ORM on top of node-sql. It's not difficult to do, I've [done it before...](https://github.com/taoeffect/dragonfly-db).

Looks like [Waterline](https://github.com/balderdashy/waterline) makes this simple to do! 😄 

There's also a Waterline fork called [Offshore](https://github.com/Atlantis-Software/offshore).

See: #85

**Comment by taoeffect** [comment]
While I could not find an ORM that uses SQL properly I did find two db agnostic query builders:
- https://github.com/brianc/node-sql
- https://hiddentao.github.io/squel/

Adapters:
- https://github.com/mapbox/node-sqlite3
- https://github.com/brianc/node-postgres
- https://github.com/felixge/node-mysql

**Comment by taoeffect** [comment]
Came across an ORM called [firenze](https://github.com/fahad19/firenze) that (also) doesn't use parameterized queries (because like bookshelf it uses [knex](https://github.com/tgriesser/knex)), but _might_ be possible to extend using node-sql instead of Knex (maybe with some tweaks). This might also be possible to do with bookshelf.

Adding `research` label.

EDIT: apparently knex is (unfortunately) used by a crapton of ORMs. The good news is that if it fixes itself all of these will become usable: [bookshelf](https://github.com/tgriesser/bookshelf/), [objection.js](https://github.com/Vincit/objection.js), [firenze](https://github.com/fahad19/firenze). And, alternatively, one would simply need to modify (or create a wrapper around) node-sql that duplicates knex API to get instant "correct behavior" out of 3 ORMs.

**Comment by taoeffect** [comment]
Closing this issue since we now have successfully switched from Sequelize to Waterline in 1e6d67f.

Ensuring that Waterline is properly using SQL (by using node-sql) is the subject of #85.
